#config_version=5

switches:
  s_left_flipper:
    number:
    tags: left_flipper
  s_right_flipper:
    number:
    tags: right_flipper

coils:
  c_flipper_left_main:
    number:
  c_flipper_left_hold:
    number:
    allow_enable: true
  c_flipper_right_main:
    number:
  c_flipper_right_hold:
    number:
    allow_enable: true

playfields:
  playfield:
    tags: default
    default_source_device: None

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
    enable_events: machine_reset_phase_3
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
    enable_events: machine_reset_phase_3

displays:
  window:
    width: 800
    height: 600
    
slide_player:
  init_done: welcome_slide
  mode_attract_started: attract_started

slides:
  welcome_slide:
    widgets:
      - type: text
        text: PINBALL!
        
  attract_started:
    widgets:
      - text: ATTRACT MODE
        type: text